const channelList = [
  {
    id: 1,
    title: "canal 8 MDP",
    description: "",
    url: "https://mardelplata.telefe.com/vivo",
    info: "https://mardelplata.mitelefe.com/horarios",
    logo: "./canal8-mdq.png",
    costo: "gratis",
    tipo: ["gratis", "in-spanish", "argentino"],
    isFavorite: false
  },
  {
    id: 2,
    title: "Canal 10 MDP",
    description: "",
    url: "https://zencast.tv/player/canal10/",
    info: "https://www.canal10mardelplata.tv/DiasyHorarios/",
    logo: "./canal-10-mdq-2.jpg",
    costo: "gratis",
    tipo: ["gratis", "in-spanish", "argentino"],
    isFavorite: false
  },
  {
    id: 3,
    title: "Netflix",
    description: "Watch Netflix on your TV.",
    url: "https://www.netflix.com/",
    info: "https://www.youtube.com/c/TopCinema/search?query=netflix",
    logo: "./netflix.png",
    costo: "subscripcion",
    tipo: ["subscripcion"],
    isFavorite: false
  },
  {
    id: 4,
    title: "Prime Video",
    description: "",
    url: "https://www.primevideo.com/",
    info: "https://www.youtube.com/c/TopCinema/search?query=prime%20video",
    logo: "./prime-video.png",
    costo: "subscripcion",
    tipo: ["subscripcion"],
    isFavorite: false
  },
  {
    id: 5,
    title: "HBOMax",
    description: "",
    url: "https://play.hbomax.com/page/urn:hbo:page:home",
    info: "https://www.youtube.com/c/TopCinema/search?query=hbo%20max",
    logo: "./hbo-max.png",
    costo: "subscripcion",
    tipo: ["subscripcion"],
    isFavorite: false
  },
  {
    id: 6,
    title: "Disney+",
    description: "",
    url: "https://www.disneyplus.com/home",
    info: "https://www.youtube.com/c/TopCinema/search?query=disney",
    logo: "./disney-plus.png",
    costo: "subscripcion",
    tipo: ["subscripcion"],
    isFavorite: false
  },
  {
    id: 7,
    title: "Star+",
    description: "",
    url: "https://www.starplus.com/es-419/home",
    info: "https://www.youtube.com/c/TopCinema/search?query=Star",
    logo: "./star-plus.png",
    costo: "subscripcion",
    tipo: ["subscripcion"],
    isFavorite: false
  },
  {
    id: 8,
    title: "Paramount+",
    description: "",
    url: "https://www.paramountplus.com/",
    info: "https://www.youtube.com/c/TopCinema/search?query=paramount%20plus",
    logo: "./paramount-plus.png",
    costo: "subscripcion",
    tipo: ["subscripcion"],
    isFavorite: false
  },
  {
    id: 9,
    title: "YouTube",
    description: "",
    url: "https://www.youtube.com",
    info: "",
    logo: "./youtube-1.png",
    costo: "gratis",
    tipo: ["gratis"],
    isFavorite: false
  },
  {
    id: 10,
    title: "Twitch",
    description: "",
    url: "https://www.twitch.tv/directory/following/live",
    info: "",
    logo: "./Twitch.png",
    costo: "gratis",
    tipo: ["gratis"],
    isFavorite: false
  },
  {
    id: 11,
    title: "Cont.ar",
    description: "",
    url: "https://www.cont.ar/",
    info: "",
    logo: "./cont.ar.png",
    costo: "gratis",
    tipo: ["gratis", "in-spanish", "argentino"],
    isFavorite: false
  },
  {
    id: 12,
    title: "CineAR Play",
    description: "",
    url: "https://play.cine.ar/inicio",
    info: "",
    logo: "./cinear-play-1.png",
    costo: "gratis",
    tipo: ["gratis", "in-spanish", "argentino"],
    isFavorite: false
  },
  {
    id: 13,
    title: "Pluto TV",
    description: "",
    url: "https://pluto.tv/on-demand",
    info: "https://www.youtube.com/c/PlutoTVLatam",
    logo: "./pluto-tv.png",
    costo: "gratis",
    tipo: ["gratis", "in-spanish"],
    isFavorite: false
  },
  {
    id: 14,
    title: "Vix",
    description: "",
    url: "https://www.vix.com/es-es/ondemand",
    info: "",
    logo: "./vix-tv.jpg",
    costo: "gratis",
    tipo: ["gratis", "in-spanish", "mexico"],
    isFavorite: false
  },
  {
    id: 15,
    title: "Playz",
    description: "",
    url: "https://www.rtve.es/playz/",
    info: "",
    logo: "./playz.png",
    costo: "gratis",
    tipo: ["gratis", "in-spanish", "españa"],
    isFavorite: false
  },
  {
    id: 16,
    title: "Canela TV",
    description: "",
    url: "https://www.canela.tv/",
    info: "",
    logo: "./canela-tv.png",
    costo: "gratis",
    tipo: ["gratis", "in-spanish"],
    isFavorite: false
  },
  {
    id: 17,
    title: "pelisplus (estrenos)",
    description: "",
    url: "https://pelisplus.io/peliculas/estreno/",
    info: "",
    logo: "./pelisplus-1.png",
    costo: "gratis",
    tipo: ["gratis"],
    isFavorite: false
  },
  {
    id: 18,
    title: "Crunchiroll",
    description: "",
    url: "https://www.crunchyroll.com/es/videos/anime",
    info: "https://www.youtube.com/c/CrunchyrollenEspa%C3%B1ol/videos",
    logo: "./crunchyroll.png",
    costo: "gratis o subscripcion",
    tipo: ["mixto"],
    isFavorite: false
  },
  {
    id: 19,
    title: "Anime Blix",
    description: "",
    url: "https://animeblix.com/animes",
    info: "",
    logo: "./animeblix-2.png",
    costo: "gratis",
    tipo: ["gratis"],
    isFavorite: false
  },
  {
    id: 20,
    title: "Anime FLV",
    description: "",
    url: "https://www3.animeflv.net/browse",
    info: "",
    logo: "./anime-flv-1.png",
    costo: "gratis",
    tipo: ["gratis"],
    isFavorite: false
  },
  {
    id: 21,
    title: "Anime Onegai",
    description: "",
    url: "https://www.animeonegai.com/es/page/home",
    info: "",
    logo: "./anime-onegai.png",
    costo: "gratis",
    tipo: ["gratis"],
    isFavorite: false
  }, 
  {
    id: 22,
    title: "LA. Cartoons",
    description: "",
    url: "https://www.lacartoons.com/",
    info: "",
    logo: "./danimados.jpg",
    costo: "gratis",
    tipo: ["gratis"],
    isFavorite: false
  }, 
  {
    id: 23,
    title: "televisionlibre",
    description: "",
    url: "https://televisionlibre.net/es/",
    info: "",
    logo: "./tv-libre.png",
    costo: "gratis",
    tipo: ["gratis"],
    isFavorite: false
  },
  {
    id: 24,
    title: "photocall.tv",
    description: "",
    url: "https://photocall.tv",
    info: "",
    logo: "./tv-ipod-icon.jpg",
    costo: "gratis",
    tipo: ["gratis"],
    isFavorite: false
  },
  {
    id: 25,
    title: "Spotify",
    description: "",
    url: "https://open.spotify.com/collection/albums",
    info: "",
    logo: "./spotify.png",
    costo: "gratis o subscripcion",
    tipo: ["mixto", "musica"],
    isFavorite: false
  },
  {
    id: 26,
    title: "YouTube Music",
    description: "",
    url: "https://music.youtube.com/",
    info: "",
    logo: "./youtube-music.png",
    costo: "gratis o subscripcion",
    tipo: ["mixto", "musica"],
    isFavorite: false
  },
  {
    id: 27,
    title: "Radios MDP",
    description: "",
    url: "https://radioarg.net/buenos-aires/mar-del-plata",
    info: "",
    logo: "./RadiosArg.Net.png",
    costo: "gratis",
    tipo: ["gratis", "argentino", "musica", "youtube"],
    isFavorite: false
  },
  {
    id: 28,
    title: "Radios Argentina",
    description: "",
    url: "https://radioarg.com/",
    info: "",
    logo: "./radios-argentina.png",
    costo: "gratis",
    tipo: ["gratis", "argentino", "musica", "youtube"],
    isFavorite: false
  },
  {
    id: 29,
    title: "Conciertos Clasicos",
    description: "",
    url: "https://www.youtube.com/watch?v=RhO5OSLZjl8&list=PLGiHySZ9dpHhqQbOtN9eAL4MxRonA6KHa",
    info: "",
    logo: "./conciertos-clasicos.png",
    costo: "gratis",
    tipo: ["gratis", "musica", "youtube"],
    isFavorite: false
  },
  {
    id: 30,
    title: "Recitales",
    description: "",
    url: "https://www.youtube.com/watch?v=KhCNz8pw3tg&list=PL54835teYYB6TXx0j37rArlHeS2Nzi9Fw&index=6",
    info: "",
    logo: "./rock.jpg",
    costo: "gratis",
    tipo: ["gratis"],
    isFavorite: false
  },
  {
    id: 31,
    title: "Red Bull TV",
    description: "",
    url: "https://www.redbull.com/ar-es/discover",
    info: "",
    logo: "./redbull-tv.png",
    costo: "gratis",
    tipo: ["gratis"],
    isFavorite: false
  },
  {
    id: 32,
    title: "Blim TV",
    description: "",
    url: "https://www.blim.com/",
    info: "",
    logo: "./vix-tv.jpg",
    costo: "gratis",
    tipo: ["gratis"],
    isFavorite: false
  },
  {
    id: 33,
    title: "Plex Tv (en ingles)",
    description: "",
    url: "https://watch.plex.tv/movies-and-shows",
    info: "",
    logo: "./Plex.webp",
    costo: "gratis",
    tipo: ["gratis"],
    isFavorite: false
  },
  {
    id: 34,
    title: "Qubit Tv",
    description: "",
    url: "https://www.qubit.tv/inicio/",
    info: "",
    logo: "./Qubit-tv.png",
    costo: "subscripcion",
    tipo: ["subscripcion"],
    isFavorite: false
  },
  {
    id: 35,
    title: "DirecTV GO",
    description: "",
    url: "https://www.directvgo.com/home/watch",
    info: "",
    logo: "./directv-go.png",
    costo: "subscripcion",
    tipo: ["subscripcion", "in-spanish", "argentino"],
    isFavorite: false
  },
  {
    id: 36,
    title: "Teatrix",
    description: "",
    url: "https://teatrix.com/",
    info: "teatro como en el teatro",
    logo: "./teatrix.png",
    costo: "subscripcion",
    tipo: ["subscripcion", "in-spanish", "argentino"],
    isFavorite: false
  },
  {
    id: 37,
    title: "Udemy",
    description: "",
    url: "https://www.udemy.com/",
    info: "Ahorra y aprende a lo grande",
    logo: "./Udemy.webp",
    costo: "subscripcion",
    tipo: ["mixto"],
    isFavorite: false
  },
 
  {
    id: 38,
    title: "TV Publica",
    description: "",
    url: "https://www.youtube.com/watch?v=n3_wuXh6jHY&ab_channel=Televisi%C3%B3nP%C3%BAblica",
    info: "",
    logo: "./TV-Publica.png",
    costo: "gratis",
    tipo: ["in-spanish", "argentino", "gratis", "youtube"],
    isFavorite: false
  },
  {
    id: 39,
    title: "Paka Paka",
    description: "",
    url: "https://www.youtube.com/watch?v=GvKCnBC80Gc&ab_channel=Pakapaka",
    info: "",
    logo: "./paka-paka.jpeg",
    costo: "gratis",
    tipo: ["in-spanish", "argentino", "gratis", "youtube"],
    isFavorite: false
  },
  {
    id: 40,
    title: "Canal Encuentro",
    description: "",
    url: "https://www.youtube.com/watch?v=o6-PQf5PHiM&ab_channel=CanalEncuentro",
    info: "",
    logo: "./canal-encuentro.png",
    costo: "gratis",
    tipo: ["in-spanish", "argentino", "gratis", "youtube"],
    isFavorite: false
  },
  {
    id: 41,
    title: "DW - Documental",
    description: "",
    url: "https://www.youtube.com/c/DWDocumental/videos",
    info: "",
    logo: "./dw-documentales.jpg",
    costo: "gratis",
    tipo: ["in-spanish", "gratis", "youtube"],
    isFavorite: false
  },
  {
    id: 42,
    title: "Depor TV",
    description: "",
    url: "https://www.youtube.com/watch?v=qlFNH-SDWTI&ab_channel=DEPORTV",
    info: "",
    logo: "./deportv.jpg",
    costo: "gratis",
    tipo: ["in-spanish", "argentino", "gratis", "deporte", "youtube"],
    isFavorite: false
  },
  {
    id: 43,
    title: "Cronica TV",
    description: "",
    url: "https://www.youtube.com/watch?v=InSydaLSSlw&ab_channel=Cr%C3%B3nicaTV",
    info: "",
    logo: "./cronica-tv.png",
    costo: "gratis",
    tipo: ["in-spanish", "argentino", "gratis", "youtube"],
    isFavorite: false
  },
  {
    id: 44,
    title: "TN en vivo",
    description: "",
    url: "https://www.youtube.com/watch?v=wHn1_QVoXGM&ab_channel=TodoNoticias",
    info: "",
    logo: "./TN-vivo.png",
    costo: "gratis",
    tipo: ["in-spanish", "argentino", "gratis", "youtube"],
    isFavorite: false
  },
  {
    id: 45,
    title: "C5N",
    description: "",
    url: "https://www.youtube.com/watch?v=wGdLaO6Mx6A&ab_channel=C5N",
    info: "",
    logo: "./c5n.png",
    costo: "gratis",
    tipo: ["in-spanish", "argentino", "gratis", "youtube"],
    isFavorite: false
  },
  {
    id: 46,
    title: "La Nacion+",
    description: "",
    url: "https://www.youtube.com/watch?v=HYxWurJ3ejE&ab_channel=LANACION",
    info: "",
    logo: "./la-nacion.png",
    costo: "gratis",
    tipo: ["in-spanish", "argentino", "gratis", "youtube"],
    isFavorite: false
  },
  {
    id: 47,
    title: "Canal 26",
    description: "",
    url: "https://www.youtube.com/watch?v=BwEO5hrk_oo&ab_channel=Canal26",
    info: "",
    logo: "./canal-26.jpg",
    costo: "gratis",
    tipo: ["in-spanish", "argentino", "gratis", "youtube"],
    isFavorite: false
  },
  {
    id: 98,
    title: "Instagram",
    description: "",
    url: "intent://instagram.com/#Intent;scheme=https;package=com.instagram.android;end",
    info: "",
    logo: "./instagram.webp",
    costo: "gratis",
    tipo: ["gratis"],
    isFavorite: false
  },
  {
    id: 99,
    title: "Whatsapp",
    description: "",
    url: "whatsapp://send?text=YoYoYo",
    info: "",
    logo: "./whatsApp.png",
    costo: "gratis",
    tipo: ["gratis"],
    isFavorite: false
  },
  {
    id: 100,
    title: "Facebook",
    description: "",
    url: "intent://facebook.com/#Intent;scheme=https;package=com.facebook.android;end",
    info: "",
    logo: "./facebook.webp",
    costo: "gratis",
    tipo: ["gratis"],
    isFavorite: false
  },
];
export default channelList;
